@startuml
left to right direction
actor Admin as A
actor Penjual as P
actor Pembeli as B

rectangle "Sistem Toko Sepatu" {
    usecase "Kelola Produk" as UC1
    usecase "Kelola Pelanggan" as UC2
    usecase "Kelola Transaksi" as UC3
    usecase "Melihat Produk" as UC4
    usecase "Melihat Riwayat Transaksi" as UC5
    
    A --> UC1 : Kelola semua
    A --> UC2 : Kelola semua
    A --> UC3 : Kelola semua
    P --> UC3 : Kelola milik sendiri
    P --> UC2 : Melihat data pelanggan
    B --> UC4 : Melihat daftar produk
    B --> UC5 : Melihat milik sendiri
}
@enduml
